language: java
install: skip

dist: trusty

jdk:
  - oraclejdk8
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./gradlew build
  - ./gradlew test