language: java
install: skip

dist: trusty
dist: xenial # sonarcloud

jdk:
  - oraclejdk11
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
sudo: false

addons:
  sonarcloud:
    organization: "yulingggg" # the key of the org you chose at step #3
    token:
      secure: "d73aebb1a8c090c56f4b0743777c3a343046b8b2" # encrypted value of your token
  apt:
    packages:
      - oracle-java8-installer


script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew test sonarqube -Dsonar.host.url=https://sonar.josdem.io